services:
  dynamodb:
    container_name: ${DYNAMO_CONTAINER_NAME}
    image: amazon/dynamodb-local
    ports:
      - "${DYNAMO_DB_PORT}:${DYNAMO_DB_PORT}"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    networks:
      - local-network

  zookeeper:
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    networks:
      - local-network

  kafka:
    container_name: ${KAFKA_CONTAINER_NAME}
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_MESSAGE_MAX_BYTES: 2097152
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2097152
      KAFKA_FETCH_MAX_BYTES: 2097152
    networks:
      - local-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_PORT}
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT}"
    networks:
      - local-network
    depends_on:
      - zookeeper
      - kafka

  redis:
    container_name: redis_fraud_engine
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - local-network

  ms-fraud-score:
    container_name: ms_fraud_score
    build:
      context: ./ms-fraud-score
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER_ADDRESS: kafka:29092
      KAFKA_CONSUMER_GROUP: fraud-score-group
      KAFKA_FRAUD_SCORE_REQUEST_TOPIC: FraudScore.Request
      KAFKA_FRAUD_SCORE_CALCULATED_TOPIC: FraudScore.Calculated
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DYNAMO_DB_ENDPOINT: http://dynamodb:${DYNAMO_DB_PORT}
      DYNAMO_DB_FRAUD_SCORES_TABLE: ddb-fraud-scores
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      - kafka
      - redis
      - dynamodb
    networks:
      - local-network

networks:
  local-network:
    driver: bridge