// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/evaluate": {
            "post": {
                "description": "Validates and evaluates a transaction request to detect potential fraud",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Evaluate a transaction for fraud detection",
                "parameters": [
                    {
                        "description": "Transaction evaluation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EvaluateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction validation successful",
                        "schema": {
                            "$ref": "#/definitions/http.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Currency": {
            "type": "string",
            "enum": [
                "USD",
                "COP",
                "EUR"
            ],
            "x-enum-varnames": [
                "USD",
                "COP",
                "EUR"
            ]
        },
        "entity.CustomerInfo": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string",
                    "example": "cust_123"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "ip_address": {
                    "type": "string",
                    "example": "192.168.1.1"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+1234567890"
                }
            }
        },
        "entity.EvaluateTransactionRequest": {
            "type": "object",
            "properties": {
                "amount_in_cents": {
                    "type": "integer",
                    "example": 10000
                },
                "currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Currency"
                        }
                    ],
                    "example": "USD"
                },
                "customer": {
                    "$ref": "#/definitions/entity.CustomerInfo"
                },
                "payment_method": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaymentMethod"
                        }
                    ],
                    "example": "CARD"
                }
            }
        },
        "entity.PaymentMethod": {
            "type": "string",
            "enum": [
                "CARD",
                "BANK_TRANSFER",
                "CRYPTO"
            ],
            "x-enum-varnames": [
                "CARD",
                "BANK_TRANSFER",
                "CRYPTO"
            ]
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "customer email is invalid"
                },
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                }
            }
        },
        "http.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Transaction validation successful"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Transaction Evaluator API",
	Description:      "API for evaluating transactions and detecting potential fraud",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
